### PR TITLE
Wrote a plugin that supports Fallout 4 VR.

### PR DESCRIPTION
**Pull request by matzman666**
Not a pull request per-se, but I didn't know where else to put it.

I wrote a plugin that supports Fallout 4 VR. It is basically a fork from the Fallout 4 plugin that adds a "VR" behind every mentioning of "Fallout4" and some small changes to add the VR specific .ba2 and .esm files, to save the correct .ini files into the profiles, and to write the local save settings into the correct .ini file.

What currently is not working is auto detection of the Fallout 4 VR (I haven't found out the reason yet). Also before Mod Organizer can detect a manually selected Fallout 4 VR installation, a file named "Fallout4VRLauncher.exe" needs to be created in the Fallout4VR installation folder. Mod Organizer checks the presents of both *[GameName].exe* and *[GameName]Launcher.exe*, but Fallout 4 VR does not come with a launcher.

Also loot needs to be adapted to work with the Fallout 4 VR plugin ([Corresponding pull request](https://github.com/LePresidente/modorganizer-lootcli/pull/6)).

### CODE REVIEW

**Comment by Silarn** [comment]
Can you push your changes into a new modorganizer-game_fallout4vr repository? At some point @LePresidente can pull the repo into his namespace but in the meantime I can simply add a build dependency to build the fallout4vr project from your repository.

The Launcher issue will have to be resolved. I'll have to double-check that code to see what we can do to bypass that check.

**Comment by Silarn** [comment]
FYI you can override the getLauncherName function within the fallout4vrgame.cpp and have it simply return Fallout4VR.exe or something.

**Comment by LePresidente** [comment]
We can use a branch for now, and i'll will clone to modorganizer-game_fallout4vr

**Comment by Silarn** [comment]
Right - I meant create a fresh repo and push to it. That would eliminate the fork problems.

**Comment by LePresidente** [comment]
Temporary merge, will revert after mirror

**Pull request merged**
